
INSERT INTO nutrient (name, description) VALUES ('루테인', '노화로 인해 감소될 수 있는 황반색소밀도를 유지하여 눈 건강에 도움을 줄 수 있습니다.');
INSERT INTO nutrient (name, description) VALUES ('아스타잔틴', '눈의 피로도 개선에 도움을 줄 수 있습니다.');
INSERT INTO nutrient (name, description) VALUES ('오메가3', '뇌세포를 보호하고 신호전달을 원할하게 하여 기억력 개선에 도움을 줍니다. 건조한 눈을 개선시켜 줍니다. 우울감을 개선하여 수면에 간접적으로 도움이 될 수 있습니다.');
INSERT INTO nutrient (name, description) VALUES ('비타민A', '세포의 성장과 재생에 꼭 필요한 영양소이며, 피부와 점막을 건강하게 유지하는데 중요합니다. 눈에서 빛을 흡수하는 세포를 만드는데 필요합니다.');
INSERT INTO nutrient (name, description) VALUES ('베타카로틴', '눈에서 빛을 흡수하는 세포를 만드는데 필요합니다.');
INSERT INTO nutrient (name, description) VALUES ('비타민C', '세포를 늙게 만드는 활성산소를 없애주는 대표적인 항산화제입니다. 다양한 면역 관련 세포 기능을 도와 면역 기능을 유지하는데 도움을 줍니다.');
INSERT INTO nutrient (name, description) VALUES ('비타민D', '칼슘 흡수를 도와주는 영양소로 뼈와 치아를 튼튼하게 유지해줍니다.');
INSERT INTO nutrient (name, description) VALUES ('아연', '면역 세포의 활성을 조절해 면역력을 높여줍니다.');
INSERT INTO nutrient (name, description) VALUES ('프로폴리스', '항산화력이 높아서 노화를 촉진하는 활성산소를 없애주는데 도움을 줍니다. 가글이나 스프레이 형태로 사용하면 입 안의 균을 줄여줍니다.');
INSERT INTO nutrient (name, description) VALUES ('칼슘', '칼슘 섭취가 부족해서 혈액 속 칼슘의 농도가 낮아지면, 뼈에서 칼슘이 녹아 나와 혈액으로 이동하고 뼈는 약해질 수 있기 때문에 칼슘을 충분히 섭취하는 것이 중요합니다.');
INSERT INTO nutrient (name, description) VALUES ('마그네슘', '근육과 신경의 활동을 조절하는 영양소로 근육 이완에 도움을 줍니다. 몸의 활력을 높여주고, 신경 안정과 수면 향상에도 도움을 줍니다.');
INSERT INTO nutrient (name, description) VALUES ('글루코사민', '연골을 구성하는 성분 중의 하나로, 관절을 건강하게 유지하도록 도와줄 수 있습니다.');
INSERT INTO nutrient (name, description) VALUES ('콘드로이친', '연골과 관절을 건강하게 유지하도록 도움을 줄 수 있습니다.');
INSERT INTO nutrient (name, description) VALUES ('MSM', 'MSM을 통해 섭취할 수 있는 황은 콜라겐을 만드는데 꼭 필요한 성분으로 관절 건강에 도움을 줄 수 있습니다.');
INSERT INTO nutrient (name, description) VALUES ('보스웰리아', '염증 반응을 조절해 관절을 건강하게 유지하도록 도움을 줄 수 있습니다.');
INSERT INTO nutrient (name, description) VALUES ('은행잎 추출물', '뇌세포를 손상시키는 물질을 감소시켜 기억력을 높이는데 도움을 줄 수 있습니다');
INSERT INTO nutrient (name, description) VALUES ('비타민B2', '에너지 생성을 도와 생활에 활력을 더해줍니다');
INSERT INTO nutrient (name, description) VALUES ('테아닌', '스트레스를 받을 때 만들어지는 호르몬을 조절해 긴장을 완화하는데 도움을 줄 수 있습니다.');
INSERT INTO nutrient (name, description) VALUES ('콜라겐', '콜라겐은 피부 보습 성분들이 잘 자리잡도록 해 피부 보습과 탄력을 유지하는데 도움을 줍니다');
INSERT INTO nutrient (name, description) VALUES ('세라마이드', '세라마이드는 피부 장벽을 만드는 영양성분으로, 수분이 빠져나가는 것을 막아 피부 보습에 도움을 줄 수 있습니다.');
INSERT INTO nutrient (name, description) VALUES ('셀레늄', '세포를 늙게 만드는 활성산소를 없애 노화를 늦춰줄 수 있고 피부가 손상되지 않도록 지켜주는 효과가 있습니다.');
INSERT INTO nutrient (name, description) VALUES ('판토텐산', '비타민B5라고도 불리는 판토텐산은 피지를 억제하고 염증을 조절하는 기능이 있기 때문에 여드름 치료에 도움을 줄 수 있습니다.');
INSERT INTO nutrient (name, description) VALUES ('가르시니아캄보지아(HCA)', '탄수화물이 지방으로 바뀌는 것을 막아, 체지방 감소에 도움을 줄 수 있습니다.');
INSERT INTO nutrient (name, description) VALUES ('키토산(키토올리고당)', '음식으로 섭취한 지방이 잘 흡수되지 않도록 방해해, 체지방 감소에 도움을 줄 수 있습니다. 콜레스테롤 흡수를 방해해 혈중 콜레스테롤 수치를 개선하는데 효과가 있습니다.');
INSERT INTO nutrient (name, description) VALUES ('녹차추출물(카테킨)', '체내 지방 대사를 활발하게 하여, 체지방 감소를 도움을 줍니다. 콜레스테롤 흡수를 방해해, 혈중 콜레스테롤 수치를 개선하는데 도움을 줄 수 있습니다.');
INSERT INTO nutrient (name, description) VALUES ('비타민 B6', '단백질을 만드는 ‘아미노산’의 대사에 필요한 영양소로, 혈관을 손상시킬 수 있는 ‘호모시스테인’이 많아지지 안도록 조절해줍니다.');
INSERT INTO nutrient (name, description) VALUES ('밀크씨슬', '활성산소로부터 간 세포를 보호하는 향산화 작용이 있어서 간 건강에 도움을 줍니다.');
INSERT INTO nutrient (name, description) VALUES ('미네랄', '인체에 필요한 미량의 무기질 영양소로. 신진대사를 촉진하거나 억제시켜줍니다.');
INSERT INTO nutrient (name, description) VALUES ('프로바이오틱스', '몸에 좋은 영향을 주는 유익균으로, 장건강에 도움을 줍니다.');
INSERT INTO nutrient (name, description) VALUES ('프락토올리고당', '프로바이오틱스(유산균)의 먹이가 되는 ‘프리바이오틱스’로 작용하여, 유익균들이 성장하기 좋은 환경을 만들고 배변활동에 도움을 줄 수 있습니다.');
INSERT INTO nutrient (name, description) VALUES ('매스틱검', '위식도 점막에 막을 형성해 위산이 직접 위벽에 닿지 않도록 방어하여 속쓰림 같은 위 불편감 개선에 도움을 줄 수 있습니다.');
INSERT INTO nutrient (name, description) VALUES ('스페인감초추출물', '위 점막에 있는 헬리코박터균의 성장을 억제해 점막을 보호하고 위 건강에 도움을 줄 수 있습니다');
INSERT INTO nutrient (name, description) VALUES ('파파야엔자임', '단백질 소화에 도움이 되는 파파인이라는 효소가 풍부해 소화에 도움을 줄 수 있습니다.');
INSERT INTO nutrient (name, description) VALUES ('유단백가수분해물', '스트레스를 낮추고 긴장을 완화하는데 도움을 주어 수면질 개선에 효과가 있습니다.');

INSERT INTO category (name) VALUES ('눈');
INSERT INTO category (name) VALUES ('면역력 / 항산화');
INSERT INTO category (name) VALUES ('뼈, 관절');
INSERT INTO category (name) VALUES ('소화(위)');
INSERT INTO category (name) VALUES ('두뇌활동');
INSERT INTO category (name) VALUES ('피부');
INSERT INTO category (name) VALUES ('다이어트');
INSERT INTO category (name) VALUES ('수면');
INSERT INTO category (name) VALUES ('간');
INSERT INTO category (name) VALUES ('대장');